name: CI

on: [push]

jobs:
  create_release:
    name: create_release
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        if: startsWith(github.ref, 'v')
        uses: actions/checkout@v1
      - name: create release
        if: startsWith(github.ref, 'v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Output Release URL File
        if: startsWith(github.ref, 'v')
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save Release URL File for publish
        if: startsWith(github.ref, 'v')
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

  build_and_release:
    needs: [create_release]
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - python3.6
          - python3.7
          - python3.8
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./make_layer.sh ${{ matrix.runtime }}

      - run: |
          mkdir opt
          cd opt
          unzip ../layer_diffoscope_${{ matrix.runtime }}.zip
          cd ..
          ls -l
          docker run -e DOCKER_LAMBDA_DEBUG=1 --rm -v "$PWD":/var/task:ro,delegated -v "$PWD"/opt/:/opt:ro,delegated lambci/lambda:${{ matrix.runtime }} tests.run 2> /tmp/test_results
          cat /tmp/test_results
          grep '^OK$' /tmp/test_results

      - name: Load Release URL File from release job
        if: startsWith(github.ref, 'v')
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Get Release File Name & Upload URL
        if: startsWith(github.ref, 'v')
        id: get_release_info
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
      - name: Upload Release Asset
        if: startsWith(github.ref, 'v')
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./layer_diffoscope_${{ matrix.runtime }}.zip
          asset_name: layer_diffoscope_${{ matrix.runtime }}.zip
          asset_content_type: application/zip
